version: '3.1'
services:
  db:
    container_name: 'postgres'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecretpassword
    ports:
      - "5432:5432"
volumes:
  lime_db: {}