@host = http://localhost:5181/api

POST {{host}}/auth/register
Content-Type: application/json

{
    "username": "lime.admin",
    "email": "lime.admin@yopmail.com",
    "password": "qwe123QWE!@#",
    "organization": "Anonymous"
}